spring.application.name=medsupply-hub
spring.datasource.url=jdbc:mysql://localhost:3306/medsupply-hub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=medsupply-hub
spring.datasource.password=medsupply-hub
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true